#!/bin/sh

percent="$(brightnessctl | grep -Po "(?<=\().*?(?=\%)")"

lvl=$(awk -v n="$percent" 'BEGIN{print int(n/34)}')
if [ "$lvl" -eq 0 ]; then
	icon="󰃜"
elif [ "$lvl" -eq 1 ]; then
	icon="󰃝"
else
	icon="󰃠"
fi

echo "{\"content\": \"$percent\", \"icon\": \"$icon\"}"
