#!/bin/sh

get_data() {
	default="0"

	volume="$(pamixer --get-volume-human | grep -Po '\d+(?=%)')"

	if [ "$volume" = "" ]; then
		icon="󰖁"
	else
		lvl=$(awk -v n="$volume" 'BEGIN{print int(n/34)}')
		if [ "$lvl" -eq 0 ]; then
			icon="󰕿"
		elif [ "$lvl" -eq 1 ]; then
			icon="󰖀"
		else
			icon="󰕾"
		fi
	fi
	echo "{\"content\": \"${volume:-${default}}\", \"icon\": \"$icon\"}"
}

[ "$1" = "" ] && get_data && exit
[ "$1" = "toggle" ] && (pamixer -t) && exit
exit
