#!/bin/sh

get_data() {
	status="$(playerctl -p spotify status)"

	icon=""
	if [ "$status" = "No players found" ]; then
		echo "{\"status\": \"\"}" && exit
	elif [ "$status" = "Paused" ]; then
		icon="󰐌"
	elif [ "$status" = "Playing" ]; then
		icon="󰏥"
	fi

	title="$(playerctl -p spotify metadata title)"
	artist="$(playerctl -p spotify metadata artist)"

	echo "{\"status\": \"$status\", \"icon\": \"$icon\", \"title\": \"$title\", \"artist\": \"$artist\"}"
}

[ "$1" = "" ] && get_data && exit
[ "$1" = "toggle" ] && (playerctl -p spotify play-pause) && exit
[ "$1" = "next" ] && (playerctl -p spotify next) && exit
[ "$1" = "previous" ] && (playerctl -p spotify previous) && exit

exit
