return {
  diagnostics = {
    error = "×",
    warn = "▲",
    hint = "•",
    info = "•",
    prefix = "▏",
    suffix = "🭵",
  },
  file_system = {
    default = "󰈚",
    symlink = "",
    folder = {
      default = "",
      empty = "",
      empty_open = "",
      open = "",
      symlink = "",
      symlink_open = "",
      arrow_open = "",
      arrow_closed = "",
    },
  },
  git = {
    added = " 󰐙 ",
    modified = " 󰻃 ",
    removed = " 󰍷 ",
    branch = " ",
  },
  gitsigns = {
    add = " ▎",
    change = " ▎",
    delete = " ",
    topdelete = " ",
    changedelete = " ▎",
    untracked = " ▎",
  },
  kinds = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
    Macro = "", -- Macro
  },
  misc = {
    dots = "󰇘",
  },
  arrows = {
    right = "",
    left = "",
    up = "",
    down = "",
  },
}
