# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/77fb31cb-1880-4b54-9aef-76e3eccd59a8";
      fsType = "ext4";
    };
    "/media" = {
      device = "/dev/disk/by-uuid/77209e93-411c-41d1-aed7-77fa3c54d4bc";
      fsType = "ext4";
    };

    "/docs" = {
      device = "/dev/disk/by-uuid/b99d161f-c7af-481c-88f6-f9c3b4aeba37";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/AAD2-8417";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/2adbe63a-a496-4d16-8a92-7afd460ceed1";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
