require("plugins.ui.icons")

require("plugins.editor.fuzzy-finder")
require("plugins.editor.buffer-util")
require("plugins.editor.file-manager")
require("plugins.editor.git")
require("plugins.editor.smart-splits")
require("plugins.editor.surround")
require("plugins.editor.todo")
require("plugins.editor.which-key")

require("plugins.ui.colorscheme")
require("plugins.ui.bufferline")
require("plugins.ui.colorizer")
require("plugins.ui.dashboard")
require("plugins.ui.mini-indentscope")
require("plugins.ui.quickfix")
require("plugins.ui.winbar")

require("plugins.coding.nvim-treesitter")
require("plugins.coding.lua")
require("plugins.coding.autocompletion")
require("plugins.coding.autopairs")
require("plugins.coding.code-action")
require("plugins.coding.formatting")
require("plugins.coding.testing")
require("plugins.coding.debugging")
require("plugins.coding.latex")
require("plugins.coding.markdown")
require("plugins.coding.typescript")
