name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13
        with:
          use-flakehub: false

      - name: Check formatting
        run: nix fmt -- --fail-on-change .

      - name: Run flake checks
        run: nix flake check --all-systems
